language: ruby
rvm:
- 2.0.0
install:
- bundle install
script: bundle exec jekyll build && bundle exec s3_website push --force
branches:
  only:
  - master
env:
  global:
  - secure: fu3oQ4EpKcuJ0+nx+/dmRMjABZ47OIIrsGD1aABLZISrHGfs6ZfZa5Vma//cEB6nMR3pMI56cAm7odDVy6hAInzVstv04C4T2CVL2kVNzqhw4eTNIiypYvaXbDUgJRg2soj5/ISy+kbQXjC38eDUgLPP/mu4ns5BF+QkY7emSXY=
  - secure: cOIu4Nlgt54GN4GYq4X5vKgpokmXRkkOZYI6XkOAvQNPHHDFdTiItSAXmE8XkERhHN2brlaKPU7nv0QidZ9/xX+eZ5FaLa6j/oi1V10wa/zy5PoMH8imTIt5swjONCKj2YXmOQn7vRWMlNga4mfJl5CTV+JtjXXvUWLo+oVegA8=
