### GENERAL SETTINGS ###

# Site settings
title: BACKEND MATTERS.
description: "Everything cloud related. Views expressed are my own and not those of AWS."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://www.backendmatters.com"

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
social:
  - title: linkedin
    url: https://linkedin.com/pub/oliver-arafat/21/30a/33/
  - title: twitter
    url: https://twitter.com/oliverarafat 
  - title: github
    url: https://github.com/arafato
  - title: google-plus
    url: https://plus.google.com/u/0/
  - title: picture-o
    url: https://speakerdeck.com/arafato
    
about: "Oliver Arafat is an Evangelist at Amazon Web Services covering Germany. Father of two, husband, serious runner and cycler."

events:
  - name: Heureka
    location: Alte Münze, Berlin
    date: May 4th
    website: http:/heureka-conference.com
    talk: How to build innovation into <br>the DNA of your Company
    talk-url: http:/heureka-conference.com/workshop-1
  - name: EnterJS
    location: darmstadtium, Darmstadt
    date: June 17-19th
    website: http://www.enterjs.de
    talk: Kosteneffiziente Qualitätssicherung <br>mit virtuellen Hardware-Labs
    talk-url: http://www.enterjs.de/abstracts#kosteneffiziente-qualitaetssicherung


    
      